config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :actor_movies
  resources :movies
  resources :addresses
  resources :actors
  resources :directors
  get '/persons', to: 'persons#index'
  get '/persons/new', to: 'persons#new'
  post '/persons/create', to: 'persons#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController

  def index
    if params[:q].present?
      if params[:q] == "director"
        @directors = Director.all
      elsif params[:q] == "actor"
        @actors = Actor.all
      end
    end
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    if params[:person_type]=="actor"
    	@person = Actor.new(person_params)
    elsif params[:person_type]=="director"
        @person = Director.new(person_params)
    end

    respond_to do |format|
      if @person.save
        format.html { redirect_to persons_path, notice: 'Person was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
  end

  def destroy
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.permit(:first_name, :last_name, :birth_date, :description)
    end
end

app/views/persons/index.html.erb
<p id="notice"><%= notice %></p>

<% if params[:q].present? %>
	<% if params[:q] == "director" %>
		<h1>Directors</h1>

		<table>
		  <thead>
			<tr>
			  <th>First name</th>
			  <th>Last name</th>
			  <th>Birth date</th>
			  <th>Description</th>
			  <th colspan="3"></th>
			</tr>
		  </thead>

		  <tbody>
			<% @directors.each do |director| %>
			  <tr>
				<td><%= director.first_name %></td>
				<td><%= director.last_name %></td>
				<td><%= director.birth_date %></td>
				<td><%= director.description %></td>
				<td><%= link_to 'Show', director %></td>
				<td><%= link_to 'Edit', edit_director_path(director) %></td>
				<td><%= link_to 'Destroy', director, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			  </tr>
			<% end %>
		  </tbody>
		</table>
	<% elsif params[:q] == "actor" %>
		<h1>Actors</h1>

		<table>
		  <thead>
			<tr>
			  <th>First name</th>
			  <th>Last name</th>
			  <th>Birth date</th>
			  <th>Description</th>
			  <th colspan="3"></th>
			</tr>
		  </thead>

		  <tbody>
			<% @actors.each do |actor| %>
			  <tr>
				<td><%= actor.first_name %></td>
				<td><%= actor.last_name %></td>
				<td><%= actor.birth_date %></td>
				<td><%= actor.description %></td>
				<td><%= link_to 'Show', actor %></td>
				<td><%= link_to 'Edit', edit_actor_path(actor) %></td>
				<td><%= link_to 'Destroy', actor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			  </tr>
			<% end %>
		  </tbody>
		</table>
	<% end %>
<% end %>
<br>

<%= link_to 'New Person', persons_new_path %>

app/views/persons/new.html.erb
<h1>New Person</h1>

<%= form_tag(:controller => "persons", :action => "create") do %>
  <%= label_tag :first_name %>  
  <%= text_field_tag(:first_name) %>
  <%= label_tag :last_name %>  
  <%= text_field_tag(:last_name) %>
  <%= label_tag :description %>  
  <%= text_field_tag(:description) %>
  <%= label_tag :birth_date %>  
  <%= date_field_tag(:birth_date)  %>
  <p>
  <%= label_tag :actor %>  
  <%= radio_button_tag(:person_type, "actor") %>
  <%= label_tag :director %> 
  <%= radio_button_tag(:person_type, "director") %>
  </p>
  <p>
  <%= submit_tag "Submit"%>
  </p>  
<% end %>  

<%= link_to 'Back', persons_path %>